name: random-one
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print something random
        id: rando
        uses: "johndmathis/workflow-test/randomNumber@v10"
        with:
          min-val: "13"
          max-val: "87"
      - name: Output rando
        run: echo "Your random number is ${{ steps.rando.outputs.random }}"
