name: random-one
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print something random
        id: rando
        uses: "LeanKit/github-actions/randomNumber@v0.0.10"
        with:
          min-val: "0"
          max-val: "0"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Output rando
        run: echo "Your random number is ${{ steps.rando.outputs.random }}"
