name: random-one
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print something random
        id: rando
        uses: "johndmathis/workflow-test/randomNumber@v7"
        with:
          min-value: 13
          max-value: 87
      - name: Output rando
        run: "The time was ${{ steps.rando.outputs.radom }}"
