name: "job-one"
on:
  pull_request:
    branches-ignore:
      - master
env:
  MY_VAR: Hi there!
  MY_OTHER_VAR: Well now
jobs:
  job1:
    name: Job One
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo $MY_VAR This is something.
