name: job-one
on:
  push:
    branches: [ master ]
  pull_request:
      branches: [ master ]
env:
  MY_VAR: Hi there!
  MY_OTHER_VAR: Well now
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print something
        run: echo $MY_VAR This is something.

